# Generated by Django 4.0.2 on 2022-03-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gadget',
            old_name='aquisition_type',
            new_name='acquisition_type',
        ),
    ]
