# Generated by Django 4.0.2 on 2022-03-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_ati', models.IntegerField(default=0)),
                ('shop', models.CharField(max_length=255, null=True)),
                ('gadget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadgets.gadget')),
            ],
        ),
    ]
