# Generated by Django 4.0.2 on 2022-03-12 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sender', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('gadget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gadgets.gadget')),
            ],
        ),
    ]
